### PR TITLE
Bitcoin cli fn take2

### PR DESCRIPTION
**Pull request by ak1n**
* changes: consolidate all bitcoin-cli and bitcoind calls into dedicated function
* rationale:
  * consolidate code
  * allow more verbose debugging (with verbose function in subsequent commits) 
* testing: ran "make" with all checks passed
* additional notes
  * some trailing whitespaces also removed (atom editor defaults do this automatically) - in dedicated initial commit
  * calls all in separate commits as no "prototype" call (variable parameters as evident in function & related comments)
  * used 1 (number) instead of True due to reading discussions on improper mutability of True & False in python2
* initial drafts here:
  * bitcoin cli fn take 1: https://github.com/GlacierProtocol/GlacierProtocol/pull/55
  * crude multi-feature draft: https://github.com/GlacierProtocol/GlacierProtocol/pull/53
* in-progress work that builds on this:
  * verbose mode: https://github.com/ak1n/GlacierProtocol/tree/verbose-mode
  * waiting on subsequent pull-requests until I ensure this pull request is acceptable
* thank you @bitcoinhodler for your feedback/assistance

Further feedback welcome!

### CODE REVIEW

**Comment by bitcoinhodler** [comment]
I think this is a good improvement, but I'm a little wary of the complexity of the API. Things like "call_type=1" aren't exactly obvious.

What if there were several functions:
`bitcoin_cli_call`
`bitcoin_cli_output`
`bitcoind_call`

Each of those three functions could then call one bigger function, passing in the necessary obtuse options.

Instead of allowing `stdout= stderr=` why not `silent=True`?

Also notice that most calls to bitcoin_cli immediately convert to JSON...so why not do that in one place?

`bitcoin_cli_json`

If I get some time this week I might try to hack around on your branch a bit to play with these ideas.

**Comment by ak1n** [comment]
I have done what you requested in this development branch/commit: https://github.com/ak1n/GlacierProtocol/commit/878da26c20966058b8613513c8bea1a071696578

There I also put in the comments call information and the various parameters needing consideration. It passes make for what it is worth.

Seem like more functions than are helpful, but either have to have function arguments or discrete functions to accommodate the various options. Re the former could simply rename the flags to clearer names as another option. Conceivably even though the functions now look ridiculous, if there is significant future dev work then they could be useful as more calls are made of various types. Let me know what you want to do.

I've completed more feature upgrades, with details listed on the readme on my fork: https://github.com/ak1n/GlacierProtocol

I don't think I'll have a lot more time to contribute to mainline glacier as I need to work towards getting my target code (with digital keys) formally audited. So let me know what you think the most useful features/parts might be (if any) re upstream merge.

Thanks for the feedback, your time is appreciated.

**Comment by bitcoinhodler** [comment]
> 
> 
> I have done what you requested in this development branch/commit: [ak1n@878da26](https://github.com/ak1n/GlacierProtocol/commit/878da26c20966058b8613513c8bea1a071696578)
> 

Ugh, I just saw this after I sent you a PR for the changes I've implemented today. I will take a look at your branch later today.

**Comment by ak1n** [comment]
No worries - since I think I made a bunch of changes since that branch I can go through your commits one by one and integrate/reference. Thank you.

**Comment by bitcoinhodler** [comment]
I've opened a new PR #58 that includes all this plus the -v verbose flag. If that gets merged first then we should just close this one.

**Pull request merged**
